version: '3'

services:
  front:
    build: 
      context: ./
      dockerfile: ./front/Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - .:/app

  server:
    build: 
    # ./server
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - ./db.json:/server/db.json
