version: '3'

services:
  front:
    build: ./front
    ports:
      - "8080:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs/


  server:
    build: ./server
    ports:
      - "9001:3000"
    volumes:
      - ./db.json:/app/server/db.json
